### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by josipbernat** [vineetchoudhary/Apple-iOS-MDM-Server#1]
Hi,

When I try to open [blog with example](https://developerinsider.co/how-to-set-up-a-simple-ios-mobile-device-management-mdm-server/) then I get message that web page isn't working any more. Can you update it?

**Comment by slthomason** [comment]
I found these:
https://developerinsider.co/how-to-create-a-verified-ios-mobile-device-management-mdm-profile/
https://medium.com/developerinsider/how-to-create-a-verified-ios-mobile-device-management-mdm-profile-9d6739b92cc1

But step #9 is incomplete and contains a very vague file reference that I can't understand (see other issue).

**Comment by vineetchoudhary** [comment]
Updated!! Thanks :)
